name-template: $RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

template: |
  ## What’s Changed

  $CHANGES

categories:
- title: '⬆️ Dependencies'
  collapse-after: 3
  labels:
  - dependencies
  - library-update
  - test-library-update
  - sbt-plugin-update
