addSbtPlugin("com.github.sbt"    % "sbt-dynver"     % "5.0.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.6.0")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"   % "0.5.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.10.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.12.1")
