addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"  % "0.6.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.15")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.6.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.24")
