---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - main
  pull_request:

jobs:
  checks:
    name: Format and style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: adopt:11
        apps: sbtn
    - run: sbtn -v scalafixAll --check
    - run: sbtn -v scalafmtCheckAll
    - run: sbtn -v scalafmtSbtCheck
    - run: sbtn -v headerCheckAll
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: adopt:11
        apps: sbtn
    - run: git submodule update --init
    - run: sbtn -v test
    - uses: GabrielBB/xvfb-action@v1.6
      with:
        run: sbt scripted
