---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    tags:
    - v*

jobs:
  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.14
    - run: sbt core/publish core/bintraySyncMavenCentral
               cli/publish cli/bintraySyncMavenCentral
               plugin/publish
